
import { Inter } from "next/font/google";
import ConnectWallet from "../components/ConnectWallet"
import { ThirdwebProvider } from "../app/providers/ThirdwebProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThirdwebProvider>
          <ConnectWallet />
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  );
}
